name: Bomber

on:
   workflow_dispatch:
   schedule:
     - cron: '30 3 * * *'
     - cron: '20 5 * * *'
     - cron: '30 6 * * *'
     - cron: '00 8 * * *'
     - cron: '00 9 * * *'
     - cron: '30 2 * * *'
     - cron: '00 3 * * *'
     


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      
      - uses: actions/checkout@v3

      
      - name: copy git

        run: git clone https://github.com/NH-hackers/multi-Bomber.git

      - name: run
        run: bash multi-Bomber/run.sh
